import pandas as pd
import os

# Define mappings for miembros del hogar
miembros_mappings = {
    'SUSPRIN': {1: 'Sí', 6: 'No'},
    'NINODEP': {1: 'Sí', 6: 'No'},
    'HIJODEP': {1: 'Sí', 6: 'No'},
    'ADULTO': {1: 'Sí', 6: 'No'},
    'PERCEP': {1: 'Sí', 6: 'No', 9: 'No Consta'},
    'INTERINP': {
        1.00: 'Menos de 500 euros',
        2.00: 'De 500 a menos de 1000 euros',
        3.00: 'De 1000 a menos de 1500 euros',
        4.00: 'De 1500 a menos de 2000 euros',
        5.00: 'De 2000 a menos de 2500 euros',
        6.00: 'De 2500 a menos de 3000 euros',
        7.00: '3000 euros o más',
        9: 'No consta'
    },
    'CATEGMH': {
        1: 'Miembro del hogar',
        2: 'Servicio doméstico',
        3: 'Huésped',
        4: 'Invitado',
        9: 'No Consta'
    },
    'RELASP': {
        1: 'Sustentador principal',
        2: 'Cónyuge o pareja',
        3: 'Hijo del sustentador principal y/o pareja',
        4: 'Padre o madre del sustentador principal',
        5: 'Padre o madre del cónyuge o pareja',
        6: 'Otra situación (con parentesco distinto de los anteriores y sin ningún parentesco)'
    },
    'SEXO': {1: 'Hombre', 6: 'Mujer', -9: 'No Consta'},
    'NACIONA': {
        1: 'Solo española',
        2: 'Solo extranjera',
        3: 'Española y extranjera',
        9: 'No Consta'
    },
    'PAISNACIM': {
        1: 'España',
        2: 'Resto de la Unión Europea (27 países)',
        3: 'Resto de Europa',
        4: 'Resto del mundo',
        9: 'No Consta'
    },
    'PAISNACION': {
        1: 'España',
        2: 'Resto de la Unión Europea (27 países)',
        3: 'Resto de Europa',
        4: 'Resto del mundo',
        9: 'No Consta'
    },
    'PAISPADRE': {
        1: 'España',
        2: 'Resto de la Unión Europea (27 países)',
        3: 'Resto de Europa',
        4: 'Resto del mundo',
        9: 'No Consta'
    },
    'PAISMADRE': {
        1: 'España',
        2: 'Resto de la Unión Europea (27 países)',
        3: 'Resto de Europa',
        4: 'Resto del mundo',
        9: 'No Consta'
    },
    'UNION': {
        1: 'Casado',
        2: 'Unión de hecho registrada',
        3: 'Pareja de hecho sin registrar',
        9: 'No Consta'
    },
    'CONVIVENCIA': {
        1: 'Conviviendo con su cónyuge',
        2: 'Conviviendo con una pareja de hecho',
        3: 'No conviviendo en pareja',
        9: 'No Consta'
    },
    'ECIVILLEGAL': {
        1: 'Soltero',
        2: 'Casado',
        3: 'Viudo',
        4: 'Separado',
        5: 'Divorciado',
        9: 'No Consta'
    },
    'SITURES': {1: 'Presente', 6: 'Ausente'},
    'SITURED': {1: 'Activo', 2: 'Inactivo', 9: 'No Consta'},
    'OCU': {1: 'Ocupado', 2: 'No ocupado', 9: 'No Consta'},
    'JORNADA': {1: 'Completa', 2: 'Parcial', 9: 'No Consta'},
    'IMPEXACP': {-9.0: ''},
    'NORDENCO': {99: ''},
    'NORDENPA': {99: ''},
    'NORDENMA': {99: ''},
    'ESTUDIOS': {
        1: 'No sabe leer o escribir o fue menos de 5 años a la escuela',
        2: 'Educación primaria completa o fue a la escuela 5 o más años',
        3: 'ESO, EGB o Bachiller Elemental (con título o sin título)',
        4: 'Bachiller, BUP, COU, Bachiller Superior, FP de Grado Medio',
        5: 'FP de Grado Superior, FPII y equivalentes',
        6: 'Grado de 240 ECTS, Diplomatura, Arquitectura o Ingeniería Técnica',
        7: 'Grado de más de 240 ECTS, Licenciatura, Arquitectura o Ingeniería',
        8: 'Doctorado universitario',
        -9: 'No consta'
    },
    'ESTUDRED': {
        1: 'Inferior a la primera etapa de Educación Secundaria',
        2: 'Primera etapa de Educación secundaria',
        3: 'Segunda etapa de Educación secundaria',
        4: 'Educación superior',
        -9: 'No consta'
    },
    'SITUACT': {
        1: 'Trabajando al menos una hora',
        2: 'Con trabajo del que está ausente (por enfermedad, vacaciones, etc.)',
        3: 'Parado/a',
        4: 'Jubilado/a, retirado/a anticipadamente',
        5: 'Estudiante',
        6: 'Dedicado/a a las labores del hogar',
        7: 'Con incapacidad laboral permanente',
        8: 'Otra situación de inactividad económica',
        -9: 'No consta'
    }
}

# Mappings for gastos file, over 370 categories of spendings
gastos_mappings = {
    'CODIGO': {
        '01111': 'Arroz',
        '01112': 'Harinas y otros cereales',
        '01113': 'Pan',
        '01114': 'Otros productos de panadería',
        '01115': 'Pizzas y quiches ',
        '01116': 'Pastas alimenticias y cuscús ',
        '01117': 'Cereales de desayuno ',
        '01118': 'Otros productos elaborados con cereales, no recogidos anteriormente',
        '01121': 'Carne de bovino fresca, refrigerada o congelada',
        '01122': 'Carne de porcino fresca, refrigerada o congelada',
        '01123': 'Carne de ovino y caprino fresca, refrigerada o congelada',
        '01124': 'Carne de ave fresca, refrigerada o congelada',
        '01125': 'Otras carnes (frescas y congeladas)',
        '01126': 'Despojos y menudillos',
        '01127': 'Charcutería y carne seca, salada o ahumada',
        '01128': 'Carnes procesadas y otras preparaciones a base de carne, frescas o congeladas',
        '01131': 'Pescados frescos o refrigerados',
        '01132': 'Pescados congelados',
        '01133': 'Mariscos frescos o refrigerados',
        '01134': 'Mariscos congelados ',
        '01135': 'Pescados y mariscos secos, ahumados o salados',
        '01136': 'Pescados y mariscos procesados y otras preparaciones de pescados y mariscos',
        '01141': 'Leche entera',
        '01142': 'Leche semidescremada y descremada',
        '01143': 'Leche conservada',
        '01144': 'Yogures y leches fermentadas',
        '01145': 'Queso y requesón',
        '01146': 'Otros productos a base de leche',
        '01147': 'Huevos',
        '01151': 'Mantequilla',
        '01152': 'Margarina y otras grasas vegetales',
        '01153': 'Aceite de oliva',
        '01154': 'Otros aceites comestibles',
        '01155': 'Otras grasas animales comestibles',
        '01160': 'Fruta congelada (nuevo código)',
        '01161': 'Cítricos (frescos o refrigerados)',
        '01162': 'Plátanos (frescos o refrigerados)',
        '01163': 'Manzanas (frescas o refrigeradas)',
        '01164': 'Peras (frescas o refrigeradas)',
        '01165': 'Frutas con hueso (frescas o refrigeradas)',
        '01166': 'Bayas (frescas o refrigeradas)',
        '01167': 'Otras frutas (frescas o refrigeradas)',
        '01168': 'Frutos secos',
        '01169': 'Frutas preparadas y en conserva',
        '01171': 'Hortalizas de hoja o de tallo (frescas o refrigeradas)',
        '01172': 'Bolsas de mezcla de lechugas (frescas o refrigeradas) ',
        '01173': 'Coles (frescas o refrigeradas)',
        '01174': 'Hortalizas cultivadas por su fruto (frescas o refrigeradas)',
        '01175': 'Hortalizas con raíz o bulbo y setas (frescas o refrigeradas)',
        '01176': 'Legumbres y hortalizas secas',
        '01177': 'Legumbres y hortalizas procesadas y otras preparaciones a base de legumbres y hortalizas',
        '01178': 'Legumbres y hortalizas congeladas',
        '01179': 'Aceitunas ',
        '0117A': 'Patatas',
        '0117B': 'Snacks ',
        '0117C': 'Productos derivados de las patatas, mandioca y otros tubérculos',
        '01181': 'Azúcar',
        '01182': 'Confitura, mermelada y miel',
        '01183': 'Chocolate',
        '01184': 'Confitería',
        '01185': 'Helados',
        '01186': 'Edulcorantes ',
        '01191': 'Salsas y condimentos',
        '01192': 'Sal, especias y hierbas culinarias',
        '01193': 'Alimentos para bebé',
        '01194': 'Comidas preparadas ',
        '01195': 'Productos dietéticos',
        '01199': 'Otros productos alimenticios no declarados anteriormente',
        '01211': 'Café, no en cápsulas',
        '01212': 'Café en cápsulas ',
        '01213': 'Te e infusiones',
        '01214': 'Bebidas de cacao y chocolate en polvo',
        '01221': 'Agua mineral',
        '01222': 'Bebidas refrescantes con o sin gas',
        '01223': 'Bebidas energéticas ',
        '01224': 'Bebidas isotónicas ',
        '01225': 'Zumos de frutas y/o de vegetales',
        '02111': 'Espirituosos y licores',
        '02112': 'Otras bebidas basadas en espirituosos licores sin alcohol',
        '02121': 'Vinos de uva',
        '02122': 'Vinos de otras frutas',
        '02123': 'Vinos generosos',
        '02124': 'Otras bebidas a base de vino. vino sin alcohol ',
        '02131': 'Cerveza de baja fermentación(lager, pilsen,...)',
        '02132': 'Cerveza de alta fermentación (ale, porter,...)',
        '02133': 'Cerveza baja en alcohol o sin alcohol ',
        '02134': 'Bebidas a base de cerveza ',
        '02201': 'Cigarrillos',
        '02202': 'Puros y pequeños cigarros',
        '02203': 'Otros tabacos',
        '03110': 'Telas',
        '03121': 'Prendas de vestir para hombre confeccionada o hecha a medida',
        '03122': 'Prendas de vestir de mujer confeccionada o hecha a medida',
        '03123': 'Prendas de vestir para niños (de 3 a 13 años) y bebés (menos de 3 años) confeccionada o hecha a medida',
        '03131': 'Complementos y accesorios de prendas de vestir',
        '03132': 'Artículos de mercería',
        '03141': 'Limpieza, conservación y teñido de prendas de vestir',
        '03142': 'Reparación y alquiler de prendas de vestir ',
        '03211': 'Calzado de hombre',
        '03212': 'Calzado de mujer',
        '03213': 'Calzado de niños (de 3 a 13 años) y bebés (menos de 3 años)',
        '03220': 'Reparación, alquiler de calzado y otros servicios relacionados',
        '04110': 'Alquileres reales (vivienda principal)',
        '04121': 'Alquileres reales (otras viviendas no vacacionales, ni por motivos de enseñanza)',
        '04122': 'Alquileres reales (otras viviendas por motivos de enseñanza) ',
        '04123': 'Alquileres de garaje (vivienda principal)',
        '04124': 'Alquileres de garaje (otras viviendas)',
        '04129': 'Otros alquileres',
        '04210': 'Alquileres imputados a la vivienda principal en propiedad',
        '04221': 'Alquileres imputados a otras viviendas a disposición del hogar en propiedad',
        '04222': 'Alquileres imputados a la vivienda principal, cedida gratuita o semigratuitamente',
        '04223': 'Alquileres imputados a otras viviendas a disposición del hogar, cedidas gratuita o semigratuitamente',
        '04310': 'Materiales para el mantenimiento y las reparaciones corrientes de la vivienda cuando la reparación la realiza el propio hogar',
        '04321': 'Servicios de fontanería ',
        '04322': 'Servicios de electricidad ',
        '04323': 'Servicios de mantenimiento de sistemas de calefacción individual ',
        '04324': 'Servicios de pintura ',
        '04325': 'Servicios de carpintería ',
        '04329': 'Servicios de albañilería y otros servicios de mantenimiento de la vivienda',
        '04411': 'Suministro de agua (vivienda principal, garajes y trasteros ligados a la vivienda principal )',
        '04412': 'Suministro de agua (otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04421': 'Servicio de recogida de basura (vivienda principal; garajes y trasteros ligados a la vivienda principal)',
        '04422': 'Servicio de recogida de basura (otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04431': 'Servicio de saneamiento (vivienda principal, garajes y trasteros ligados a la vivienda principal)',
        '04432': 'Servicio de saneamiento (otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04441': 'Gastos comunitarios y otros servicios relativos a la comunidad (vivienda principal,garajes y trasteros ligados a la vivienda principal)',
        '04442': 'Gastos comunitarios y otros servicios relativos a la comunidad (otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04443': 'Servicios de seguridad (vivienda principal, garajes y trasteros ligados a la vivienda principal) ',
        '04444': 'Servicios de seguridad (de otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04448': 'Otros servicios relativos a la vivienda principal (garajes y trasteros ligados a la vivienda principal) ',
        '04449': 'Otros servicios relativos a otras viviendas (garajes y trasteros no ligados a la vivienda principal, etc) ',
        '04511': 'Electricidad (vivienda principal garajes y trasteros ligados a la vivienda principal)',
        '04512': 'Electricidad (otras viviendas; garajes y trasteros no ligados a la vivienda principal, etc)',
        '04521': 'Gas ciudad y natural (vivienda principal)',
        '04522': 'Gas ciudad y natural (otras viviendas)',
        '04523': 'Gas licuado (vivienda principal)',
        '04524': 'Gas licuado (otras viviendas)',
        '04531': 'Combustibles líquidos (vivienda principal)',
        '04532': 'Combustibles líquidos (otras viviendas)',
        '04541': 'Carbón (vivienda principal) ',
        '04542': 'Carbón (otras viviendas) ',
        '04548': 'Otros combustibles sólidos (vivienda principal)',
        '04549': 'Otros combustibles sólidos (otras viviendas)',
        '05111': 'Muebles para el hogar',
        '05112': 'Muebles de jardín',
        '05113': 'Lamparas ',
        '05114': 'Muebles de bebé ',
        '05115': 'Artículos de amueblamiento',
        '05121': 'Alfombras y moquetas',
        '05122': 'Otros revestimientos de suelos',
        '05123': 'Servicios de instalación de moquetas y revestimientos de suelos ',
        '05130': 'Servicios de reparación de muebles, alfombras y revestimientos de suelos',
        '05201': 'Cortinas y tapicerías ',
        '05202': 'Ropa de cama ',
        '05203': 'Mantelerías y ropa de cocina y baño ',
        '05204': 'Reparación de textiles del hogar ',
        '05209': 'Otros artículos textiles para el hogar ',
        '05311': 'Frigoríficos, congeladores y frigoríficos congeladores',
        '05312': 'Lavadoras, secadoras y lavavajillas',
        '05313': 'Cocinas, hornos y microondas',
        '05314': 'Aparatos de calefacción, de aire acondicionado, calentadores de agua y campanas extractoras',
        '05315': 'Aparatos de limpieza',
        '05319': 'Otros grandes aparatos del hogar',
        '05321': 'Electrodomésticos para el procesamiento de alimentos ',
        '05322': 'Cafeteras y teteras eléctricas y similares ',
        '05323': 'Planchas de ropa ',
        '05324': 'Tostadoras y grills ',
        '05329': 'Otros pequeños electrodomésticos',
        '05330': 'Reparaciones y alquilerde todos los aparatos del hogar',
        '05401': 'Cristalería, vajilla, vidrio, cerámica y porcelana ',
        '05402': 'Cuberterías',
        '05403': 'Utensilios de cocina y menaje y otros artículos para el hogar no eléctricos',
        '05404': 'Reparación de cristalería, vajilla, cubertería y otros utensilios del hogar no eléctricos',
        '05511': 'Herramientas eléctricas y accesorios',
        '05512': 'Reparación, leasing y alquiler, de herramientas eléctricas y accesorios ',
        '05521': 'Herramientas y accesorios no eléctricos',
        '05522': 'Accesorios de ferretería',
        '05523': 'Reparación de herramientas y accesorios no eléctricos ',
        '05611': 'Productos de limpieza y mantenimiento',
        '05612': 'Otros productos no duraderos para el hogar',
        '05621': 'Servicio doméstico (excluidos pagos a la seguridad social)',
        '05622': 'Pagos a la seguridad social del servicio doméstico',
        '05623': 'Servicios de lavandería y tintorería de artículos de hogar ',
        '05624': 'Alquiler de mobiliario y enseres ',
        '05629': 'Otros servicios domésticos y para el hogar',
        '06111': 'Productos farmacéuticos',
        '06112': 'Productos homeopáticos ',
        '06121': 'Prueba de embarazo y dispositivos anticonceptivos no orales ',
        '06129': 'Otros productos médicos',
        '06131': 'Gafas graduadas y lentes de contacto ',
        '06132': 'Audífonos ',
        '06133': 'Reparación de aparatos y material terapéuticos ',
        '06139': 'Otros aparatos y material terapéuticos',
        '06211': 'Medicina generaly pediatría (ambulatoria)',
        '06212': 'Médico especialista (ambulatorio) ',
        '06220': 'Servicios dentales',
        '06231': 'Servicios de análisis clínicos y pruebas diagnósticas',
        '06232': 'Servicios de rehabilitación, alquiler de equipo terapéutico, servicios de ambulancias y tratamientos termales',
        '06239': 'Otros servicios paramédicos ambulatorios',
        '06300': 'Servicios hospitalarios',
        '07111': 'Automóviles nuevos',
        '07112': 'Automóviles de segunda mano',
        '07120': 'Motos y ciclomotores',
        '07130': 'Bicicletas',
        '07211': 'Neumáticos ',
        '07212': 'Compra de piezas de repuesto de vehículos personales',
        '07213': 'Accesorios de vehículos personales ',
        '07221': 'Gasóleo ',
        '07222': 'Gasolina ',
        '07223': 'Otros carburantes para vehículos personales',
        '07224': 'Lubricantes, anticongelantes, etc',
        '07230': 'Mantenimiento y reparaciones de vehículos personales en talleres',
        '07241': 'Alquiler de plazas de aparcamiento, de garajes , de vehículos para personas y otros servicios ncop',
        '07242': 'Aparcamientos públicos y parquímetros',
        '07243': 'Servicios de peaje de vehiculos personales',
        '07244': 'Autoescuela y gastos relacionados con el carnet de conducir ',
        '07245': 'Inspección técnica de vehículos ',
        '07311': 'Tren de cercanías',
        '07312': 'Tren de largo recorrido',
        '07313': 'Metro y tranvía',
        '07321': 'Autobús urbano no escolar',
        '07322': 'Autobús y autocar interurbano no escolar ',
        '07323': 'Transporte escolar',
        '07324': 'Taxi y coche de alquiler con conductor',
        '07331': 'Vuelos nacionales',
        '07332': 'Vuelos internacionales ',
        '07341': 'Transporte de pasajeros por mar',
        '07342': 'Transporte de pasajeros por vías navegables interiores ',
        '07350': 'Transporte combinado de pasajeros',
        '07361': 'Funicular, teleférico y telesilla',
        '07362': 'Servicios de mudanza y guardamuebles',
        '07369': 'Otros servicios de transporte (no contemplado en otra parte)',
        '08101': 'Servicios postales de cartas',
        '08109': 'Otros servicios postales paquetería ',
        '08201': 'Equipos de teléfono fijo ',
        '08202': 'Equipos de teléfono movil ',
        '08203': 'Otros equipos de teléfono y fax ',
        '08204': 'Reparación de equipos de teléfono y fax ',
        '08301': 'Servicios de teléfonos fijos',
        '08302': 'Servicios de teléfonos móviles',
        '08303': 'Servicios relacionados con internet',
        '08304': 'Servicios integrados de telecomunicaciones ',
        '08309': 'Otros servicios de transmisión de información',
        '09111': 'Equipos no portátiles para la recepción, registro y reproducción de sonido',
        '09112': 'Equipos no portátiles para la recepción, registro y reproducción audiovisual',
        '09113': 'Dispositivos portátiles de imagen y sonido ',
        '09119': 'Otros equipos para la recepción, registro y reproducción de sonido e imagen ',
        '09121': 'Cámaras y otros equipos fotográficos y cinematográficos',
        '09122': 'Accesorios para equipos fotográficos y cinematográficos ',
        '09123': 'Instrumentos ópticos',
        '09131': 'Ordenadores personales',
        '09132': 'Accesorios para equipos de procesamiento de la información ',
        '09133': 'Software',
        '09134': 'Calculadoras y otro material de procesamiento de la información ',
        '09141': 'Soportes pregrabados y suscripción a servicios en streaming',
        '09142': 'Soportes no grabados ',
        '09149': 'Otros soportes ',
        '09150': 'Reparación de equipos audiovisuales, fotográficos y de procesamiento de la información',
        '09210': 'Grandes equipos para el ocio y la cultura al aire libre',
        '09221': 'Instrumentos musicales',
        '09222': 'Grandes equipos para el ocio y la cultura en lugares cubiertos',
        '09230': 'Mantenimiento y reparación de otros bienes duraderos para el ocio y la cultura',
        '09311': 'Juegos y hobbies',
        '09312': 'Juguetes y artículos de fiesta ',
        '09321': 'Equipo para deporte (tanto al aire libre como en lugares cubiertos)',
        '09322': 'Equipo para acampada y ocio al aire libre ',
        '09323': 'Reparacion de equipo para deporte, acampada y ocio al aire libre ',
        '09331': 'Productos de jardineria',
        '09332': 'Plantas y flores ',
        '09341': 'Compra de mascotas',
        '09342': 'Artículos relativos a mascotas',
        '09350': 'Servicios veterinarios y otro tipo de servicios para mascotas',
        '09411': 'Servicios recreativos y deportivos - asistencia',
        '09412': 'Servicios recreativos y deportivos - participación ',
        '09421': 'Cines, teatros y espectáculos',
        '09422': 'Museos, bibliotecas y parques zoológicos',
        '09423': 'Cuotas por licencia y suscripciones a redes de tv y radio',
        '09424': 'Alquiler de equipos y accesorios culturales (ordenadores, tv,)',
        '09425': 'Servicios fotográficos ',
        '09429': 'Otros servicios culturales',
        '09430': 'Juegos de azar',
        '09511': 'Novelas y libros infantiles ',
        '09512': 'Libros de texto',
        '09513': 'Otros libros de no ficción',
        '09514': 'Descarga de libros electrónicos y otros servicios relacionados con los libros ',
        '09521': 'Periódicos',
        '09522': 'Revistas ',
        '09530': 'Impresos diversos',
        '09541': 'Artículos de papelería (cuadernos, sobres, libretas,)',
        '09549': 'Otros artículos de papelería y pintura',
        '09601': 'Paquetes turísticos nacionales',
        '09602': 'Paquetes turísticos internacionales',
        '10111': 'Primer ciclo de educación infantil (0-3 años) (grupo 01 cned-p-2014)',
        '10112': 'Segundo ciclo de educaci��n infantil (3-6 años) (grupo 02 cned-p-2014)',
        '10113': 'Enseñanzas no regladas relacionadas con el primer ciclo de educación infantil (0-3 años)',
        '10114': 'Enseñanzas no regladas relacionadas con el segundo ciclo de educación infantil (3-6 años)',
        '10121': 'Educación primaria (nivel 1: grupos 11,12 y 13 cned-p-2014)',
        '10122': 'Enseñanzas no regladas relacionadas con la educación primaria',
        '10211': 'Educación secundaria obligatoria: cursos 1º, 2º y 3º (grupos 21, 22 y 23 cned-p-2014)',
        '10212': 'Educación secundaria obligatoria: 4º curso (grupo 31 cned-p-2014)',
        '10213': 'Enseñanzas no regladas relacionadas con la educación secundaria obligatoria: cursos 1º, 2º y 3º',
        '10214': 'Enseñanzas no regladas relacionadas con la educación secundaria obligatoria: 4º curso',
        '10221': 'Bachillerato (grupo 32 cned-p-2014)',
        '10222': 'Formación profesional de grado medio, formación profesional básica y otras enseñanzas secundarias profesionales (grupos 33 a 38 cned-p-2014)',
        '10223': 'Educación postsecundaria no superior (nivel 4 cned-p-2014)',
        '10224': 'Enseñanzas no regladas relacionadas con bachillerato',
        '10225': 'Enseñanzas no regladas relacionadas con formación profesional de grado medio y similares',
        '10301': 'Formación profesional de grado superior y otras enseñanzas equivalentes (nivel 5 cned-p-2014)',
        '10302': 'Grados universitarios de 240 créditos ects y equivalentes (nivel 6 cned-p-2014)',
        '10303': 'Grados universitarios de más de 240 créditos ects, másteres, especialidades en ciencias de la salud, doctorados y equivalentes (niveles 7 y 8 cned-p-2014)',
        '10304': 'Enseñanzas no regladas relacionadas con formación profesional de grado superior y equivalentes',
        '10305': 'Enseñanzas no regladas relacionadas con grados universitarios de 240 créditos ects y equivalentes',
        '10306': 'Enseñanzas no regladas relacionadas con grados universitarios de más de 240 créditos ects y equivalentes',
        '10400': 'Educación no formal (nivel 9 cned-p-2014)',
        '11111': 'Menú del día en bares y restaurantes',
        '11112': 'Comidas y cenas en restaurantes',
        '11113': 'Consumiciones en bares y cafeterías',
        '11114': 'Consumiciones en pubs y discotecas',
        '11115': 'Banquetes, ceremonias y otras celebraciones',
        '11116': 'Servicios de comida rápida y comida para llevar ',
        '11121': 'Comedores (excepto escolares y universitarios)',
        '11122': 'Comedores escolares y universitarios',
        '11130': 'Comidas y bebidas en otros hogares ',
        '11201': 'Servicios de alojamiento en hoteles, moteles y hostales',
        '11202': 'Camping, albergues y similares',
        '11203': 'Servicios de alojamiento por motivos de enseñanza',
        '11204': 'Servicios de alojamiento en apartamentos vacacionales ',
        '12111': 'Peluquería para hombres y niños ',
        '12112': 'Peluquería para mujeres ',
        '12113': 'Tratamientos de estética personal',
        '12121': 'Aparatos eléctricos para el cuidado personal',
        '12122': 'Reparación de aparatos eléctricos para el cuidado personal',
        '12131': 'Artículos no eléctricos para el cuidado personal',
        '12132': 'Productos de aseo personal ',
        '12311': 'Joyería y bisutería',
        '12312': 'Relojería',
        '12313': 'Reparación de joyería, bisutería y relojería',
        '12321': 'Artículos de viaje, bolsos y bolsas de uso personal',
        '12322': 'Articulos para bebé',
        '12323': 'Reparación de otros efectos personales',
        '12328': 'Artículos funerarios ',
        '12329': 'Otros artículos personales',
        '12401': 'Servicios de cuidado de niños',
        '12402': 'Residencias para personas dependientes',
        '12403': 'Servicios de cuidado y mantenimiento de personas dependientes en su hogar ',
        '12404': 'Otros servicios de protección social ',
        '12521': 'Seguros ligados a la vivienda (vivienda principal)',
        '12522': 'Seguros ligados a la vivienda (otras viviendas) ',
        '12530': 'Seguros privados de enfermedad y accidente',
        '12541': 'Seguros de vehículos',
        '12542': 'Seguros de viaje y equipaje',
        '12551': 'Seguros de responsabilidad civil (excepto los derivados de la utilización de vehículos personales)',
        '12552': 'Seguros de enterramiento',
        '12559': 'Otros seguros',
        '12620': 'Otros servicios financieros no declarados en otra parte',
        '12701': 'Tasas administrativas',
        '12702': 'Servicios jurídicos y contables ',
        '12703': 'Servicios funerarios ',
        '12704': 'Otros servicios no declarados anteriormente',
        '12810': 'Dinero de bolsillo a menores residentes en el hogar',
        '12820': 'Remesas a miembros del hogar no residentes en la vivienda'
    },
}

# Mappings for hogares file 
hogares_mappings = {
    'TIPHOGAR': {
        1: 'Hogar unipersonal',
        2: 'Hogar de 2 adultos sin niños dependientes',
        3: 'Otros hogares sin niños dependientes',
        4: 'Hogar de 1 adulto con 1 o más niños dependientes',
        5: 'Hogar de 2 adultos con 1 o más niños dependientes',
        6: 'Otros hogares con niños dependientes'
    },
    'TAMAMU': {
        1: 'Menos de 10.000 habitantes',
    },
}

def apply_gastos_castings(df):
    columns_to_cast = [
        'GASTO', 'PORCENDES', 'PORCENIMP', 'CANTIDAD', 'GASTOMON',
        'GASTNOM1', 'GASTNOM2', 'GASTNOM3', 'GASTNOM4', 'GASTNOM5'
    ]
    for column in columns_to_cast:
        if column in df.columns:
            df[column] = df[column].astype(float).round(2)
    
    if 'FACTOR' in df.columns:
        df['FACTOR'] = df['FACTOR'].astype(float).round(6)
    
    return df

def enrich_csv(input_file, output_file, mapping):
    # Read the CSV file
    df = pd.read_csv(input_file)
    
    # Apply mappings to each column
    for column, column_mapping in mapping.items():
        if column in df.columns:
            df[column] = df[column].map(column_mapping).fillna(df[column])
    
    # Convert columns to appropriate data types and format decimals
    if 'gastos' in input_file:
        df = apply_gastos_castings(df)
    
    # Write the enriched DataFrame to a new CSV file
    df.to_csv(output_file, index=False)
    print(f"Enriched file saved as {output_file}")

# Directory containing the CSV files
directory = '.'

# Explicitly process each file with its corresponding mapping
files_to_process = [
    #('miembros_2023.csv', miembros_mappings),
    ('gastos_2023.csv', gastos_mappings),
    #('hogares_2023.csv', hogares_mappings)
]

for filename, mapping in files_to_process:
    input_file = os.path.join(directory, filename)
    output_file = os.path.join(directory, f"{os.path.splitext(filename)[0]}_enriched.csv")
    
    if os.path.exists(input_file):
        enrich_csv(input_file, output_file, mapping)
    else:
        print(f"File {input_file} not found.")

print("Enrichment process completed.")